version: '3.8'
services:
  mongo-secondary1:
      image: mongo
      command: mongod --port 27017 --dbpath /data/db --replSet replica01
      ports:
      - "27018:27017"
      networks:
      - red1

  mongo-secondary2:
    image: mongo
    command: mongod --port 27017 --dbpath /data/db --replSet replica01
    ports:
    - "27019:27017"
    networks:
    - red1

  mongo-secondary3:
    image: mongo
    command: mongod --port 27017 --dbpath /data/db --replSet replica01
    ports:
    - "27020:27017"
    networks:
    - red1

  mongo-primary:
    image: mongo
    command: mongod --port 27017 --dbpath /data/db --replSet replica01
    ports:
      - "27017:27017"
    networks:
      - red1
    depends_on:
      - mongo-secondary1
      - mongo-secondary2
      - mongo-secondary3

  redis_stack:
    image: redis/redis-stack
    container_name: stack2
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - red1
    depends_on:
      - mongo-primary
      - mongo-secondary1
      - mongo-secondary2
      - mongo-secondary3

  backend_app:
    image: node_mongo_api:v2
    container_name: "node_app"
    ports:
      - "3000:3000"
    networks:
      - red1
    environment:
      REDIS_HOST: stack2
      REDIS_PORT: 6379
      MONGO_URL: mongodb://mongo-primary:27017,mongo-secondary1:27017,mongo-secondary2:27017,mongo-secondary3:27017/?replicaSet=replica01
    depends_on:
      - redis_stack
      - mongo-primary
      - mongo-secondary1
      - mongo-secondary2
      - mongo-secondary3

networks:
  red1: