version: '3.8'
services:
  mongo-secondary1:
    image: mongo
    container_name: mondongo_sec1
    command: mongod --replSet replica01
    ports:
      - "27018:27017"
    networks:
      backend:
        ipv4_address: 172.50.0.7

  mongo-secondary2:
    image: mongo
    container_name: mondongo_sec2
    command: mongod --replSet replica01
    ports:
      - "27019:27017"
    networks:
      backend:
        ipv4_address: 172.50.0.6

  mongo-secondary3:
    image: mongo
    container_name: mondongo_sec3
    command: mongod --replSet replica01
    ports:
      - "27020:27017"
    networks:
      backend:
        ipv4_address: 172.50.0.5

  mongo-primary:
    image: mongo
    container_name: mondongo_primary
    command: mongod --replSet replica01
    ports:
      - "27017:27017"
    healthcheck:
      test: >
        echo "try { rs.status() } catch (err) { 
          rs.initiate({
            _id: 'replica01', 
            members: [
              { _id: 0, host: '172.50.0.4:27017', priority: 1 },
              { _id: 1, host: '172.50.0.7:27017', priority: 0.5 },
              { _id: 2, host: '172.50.0.6:27017', priority: 0.5 },
              { _id: 3, host: '172.50.0.5:27017', priority: 0.5 }
            ]
          }) 
        }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30
    networks:
      backend:
        ipv4_address: 172.50.0.4
    depends_on:
      - mongo-secondary1
      - mongo-secondary2
      - mongo-secondary3

  redis_stack:
    image: redis/redis-stack
    container_name: stack2
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      backend:
        ipv4_address: 172.50.0.3
    depends_on:
      - mongo-primary
      - mongo-secondary1
      - mongo-secondary2
      - mongo-secondary3

  backend_app:
    image: isidroitt/node_mongo_api 
    container_name: "node_app"
    ports:
      - "3000:3000"
    networks:
      backend:
        ipv4_address: 172.50.0.2
    environment:
      REDIS_HOST: 172.50.0.3
      REDIS_PORT: 6379
      MONGO_URL: mongodb://172.50.0.4:27017,172.50.0.5:27017,172.50.0.6:27017,172.50.0.7:27017/AvanceAcademicoTecNM?replicaSet=replica01
    depends_on:
      - redis_stack
      - mongo-primary
      - mongo-secondary1
      - mongo-secondary2
      - mongo-secondary3

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.0.0/24
